# Generated by Django 3.2.7 on 2021-10-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='Полное имя клиента:')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('describe', models.TextField(verbose_name='Описание')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
